<!DOCTYPE html>
<html>
<head>
    <title>Combining HTML and PHP</title>
    <meta charset="UTF-8" />
</head>
<body>
	<p>I am HTML</p>
	<?php echo '<p>I am HTML, generated by PHP</p>'; ?>
</body> 
</html>